// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjtgluygrwqztdroftse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdGdsdXlncndxenRkcm9mdHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTkxNzAsImV4cCI6MjA1Nzk5NTE3MH0.6v2j7Ry9C2CyBhfISj5Kar4J3I5xGqHuZFrMJBUKG48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);